version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash-dev
    restart: always
    user: 'root'
    ports:
      - "8050:8050"
      - "80:80"
    volumes:
      - .:/app
      - /var/log/nginx:/var/log/nginx
      - /var/log/supervisor:/var/log/supervisor
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
