version: '3.8'

services:
  dev:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: dev
      restart: always
      user: 'root'
      privileged: true
      ports:
          - "8080:8080"
      volumes:
          - ./ods:/app
