apiVersion: apps/v1
kind: Deployment
metadata:
  name: painel-ods
  labels:
    app: painel-ods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: painel-ods
  template:
    metadata:
      labels:
        app: painel-ods
    spec:
      containers:
      - name: painel-ods
        image: painel-ods:latest
        ports:
        - containerPort: 8050
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8050
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8050
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: painel-ods
spec:
  selector:
    app: painel-ods
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: painel-ods
spec:
  to:
    kind: Service
    name: painel-ods
  port:
    targetPort: 8050 