apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: painel-ods
  namespace: colocation-imb
  labels:
    app: painel-ods
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: "https://github.com/wmodanez/dash-ods.git"
      ref: "develop"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
        - name: DEBUG
          value: "False"
        - name: PORT
          value: "8050"
        - name: HOST
          value: "0.0.0.0"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: USER_UID
          value: "1001"
        - name: USER_NAME
          value: "python"
  output:
    to:
      kind: ImageStreamTag
      name: painel-ods:latest