apiVersion: apps/v1
kind: Deployment
metadata:
  name: painel-ods
  namespace: colocation-imb
  labels:
    app: painel-ods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: painel-ods
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: painel-ods
    spec:
      securityContext:
        fsGroup: 1001070000
        runAsNonRoot: true
        runAsUser: 1001070000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: init-db
        image: quay.apps.dc1openshiftadm.cloud.go.gov.br/dc1openshiftprod_colocation-imb/painel-ods:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            cp -r /app/db-init/* /app/db/
            chmod -R g+w /app/db
            rm -rf /app/db-init
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsUser: 1001070000
        volumeMounts:
        - name: app-data
          mountPath: /app/db
      containers:
      - name: painel-ods
        image: quay.apps.dc1openshiftadm.cloud.go.gov.br/dc1openshiftprod_colocation-imb/painel-ods:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsUser: 1001070000
        ports:
        - containerPort: 8050
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: app-data
          mountPath: /app/db
        livenessProbe:
          httpGet:
            path: /
            port: 8050
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8050
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: painel-ods-data 