apiVersion: apps/v1
kind: Deployment
metadata:
  name: painel-ods
  namespace: colocation-imb
  labels:
    app: painel-ods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: painel-ods
  template:
    metadata:
      labels:
        app: painel-ods
    spec:
      restartPolicy: Always
      serviceAccountName: imb-anyuid
      containers:
      - name: painel-ods
        image: quay.apps.dc1openshiftadm.cloud.go.gov.br/dc1openshifthom_colocation-imb/painel-ods:latest
        command: ["/k8s/openshift-entrypoint.sh"]
        ports:
        - containerPort: 8050
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: entrypoint
          mountPath: /k8s
        - name: data
          mountPath: /app/db
        readinessProbe:
          httpGet:
            path: /
            port: 8050
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8050
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: entrypoint
        configMap:
          name: openshift-entrypoint
          defaultMode: 0755
      - name: data
        persistentVolumeClaim:
          claimName: painel-ods-data 