apiVersion: apps/v1
kind: Deployment
metadata:
  name: painel-ods
  labels:
    app: painel-ods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: painel-ods
  template:
    metadata:
      labels:
        app: painel-ods
    spec:
      containers:
      - name: painel-ods
        image: painel-ods:latest
        command: ["/k8s/openshift-entrypoint.sh"]
        ports:
        - containerPort: 8050
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: entrypoint
          mountPath: /k8s
        readinessProbe:
          httpGet:
            path: /
            port: 8050
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8050
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: entrypoint
        configMap:
          name: openshift-entrypoint
          defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openshift-entrypoint
data:
  openshift-entrypoint.sh: |
    #!/bin/bash
    set -e
    
    # Adiciona o usuário atual ao /etc/passwd se necessário
    if ! whoami &> /dev/null; then
      if [ -w /etc/passwd ]; then
        echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
      fi
    fi
    
    # Inicia o Gunicorn
    exec gunicorn -w 4 -b 0.0.0.0:8050 app:server --timeout 120
---
apiVersion: v1
kind: Service
metadata:
  name: painel-ods
spec:
  selector:
    app: painel-ods
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: painel-ods
spec:
  to:
    kind: Service
    name: painel-ods
  port:
    targetPort: 8050 