apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: painel-ods-data
  namespace: colocation-imb
  labels:
    app: painel-ods
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 