apiVersion: v1
kind: Secret
metadata:
  name: ods-secrets
  labels:
    app: ods-painel
type: Opaque
stringData:
  MAINTENANCE_MODE: "false"
  SECRET_KEY: "fa04fa8f58e7807ab75f3703f15a51ea5cea9b9e0649d2f8483f6e4ddfe48b0c"
  MAINTENANCE_PASSWORD_HASH: "$2b$12$rPg89brYmj38FJBb4bMn2eHBhOKf8rv/qtmu2jGq8xCMxlmGD6eGu" 